# The following commands can be issued to the Executor

int8 EXECUTE = 0                                    # Indicating the executor to start executing
int8 CONTINUE = 1                                   # Indicating the executor to continue executing
int8 PAUSE = 2                                      # Indicating the executor to pause the execution
int8 CANCEL = 3                                     # Indicating the executor to cancel the execution

int8 command                                        # Command