string platform_id                  # related platform id

string model_info                   # platform related information for display

PlatformClass platform_class        # class of platform

float32 max_flight_duration         # in min

float32 max_flight_height           # in m AGL

float32 max_velocity                # in m/s

float32 turning_radius              # in m

SensorCapabilities[] sensor_caps    # capabilities per carried sensors
